trigger:
    - main

pool:
    vmImage: ubuntu-latest

variables:
    buildConfiguration: 'Release'

steps:
    - script: dotnet build --configurations $(buildConfigurations)
      displayName: 'dotnet build $buildConfiguration)'